### PR TITLE
fix #446

### LINKED ISSUE #446: Broken health check if no cache is used
**Describe the bug**
If no cache is configured the health check throws an exception:
```
AttributeError: 'NoneType' object has no attribute 'get_health'
```

**To Reproduce**
1. Set `CACHE_GEOCODING` and `CACHE_QUERIES` to `False`
2. Start QL
3. Curl `/health`

**Expected behavior**
Health status should be returned. 

**Additional context**
Full traceback:
```
time=2021-02-04 03:14:06.104 | level=ERROR | corr=None | from=192.168.1.5 | srv=None | subserv=None | op=log_exception | comp=server.wsgi | msg=Exception on /health [GET] | payload=None | thread=139770318101280  | process=36
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/site-packages/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.8/site-packages/connexion/decorators/uri_parsing.py", line 144, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.8/site-packages/connexion/decorators/parameter.py", line 121, in wrapper
    return function(**kwargs)
  File "/src/ngsi-timeseries-api/src/reporter/health.py", line 86, in get_health
    res = _check_not_critical(check_cache(), res, 'redis')
  File "/src/ngsi-timeseries-api/src/reporter/health.py", line 28, in check_cache
    return cache.get_health()
AttributeError: 'NoneType' object has no attribute 'get_health'
```

### PR DESCRIPTION
**Pull request by chicco785**
## Proposed changes

- fix #446
- check health improvement using default backend for the check

## Types of changes

What types of changes does your code introduce to the project: _Put
an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
      functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after
creating the PR. If you're unsure about any of them, don't hesitate to
ask. We're here to help! This is simply a reminder of what we are going
to look for before merging your code._

- [x] I have read the [CONTRIBUTING][contrib] doc
- [x] I have signed the [CLA][cla]
- [ ] I have added tests that prove my fix is effective or that my
      feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in
      downstream modules

## Further comments

N/A

[cla]: https://fiware.github.io/contribution-requirements/individual-cla.pdf
    "FIWARE Individual Contributor License Agreement"
[contrib]: https://github.com/smartsdk/ngsi-timeseries-api/blob/master/CONTRIBUTING.md
    "Contributing to QuantumLeap"

### CODE REVIEW

**Comment by chicco785** [comment]
@c0c0n3 to test properly the functionality, we should be able to pass different configurations to the embedded ql, any clue?

File: src/reporter/tests/run_tests.sh [hunk 1]
```diff
@@ -5,8 +5,7 @@ sleep 20
 
 cd ../../../
 pytest src/reporter/ \
-       --cov-report= --cov-config=.coveragerc --cov-append --cov=src/ \
-       --ignore=src/reporter/tests/test_health.py
+       --cov-report= --cov-config=.coveragerc --cov-append --cov=src/
```
Comment (chicco785) [inline src/reporter/tests/run_tests.sh:8]: we have to be careful with upper and lower cases of backend names

Comment (c0c0n3) [reply src/reporter/tests/run_tests.sh:8]: not sure what lines of code you're referring to exactly? the names in the yaml config weren't the same as those in the tests? if so, how come?

Comment (c0c0n3) [reply src/reporter/tests/run_tests.sh:8]: never mind, I think I actually spotted the issue with 'crateDB' :-)

**Comment by c0c0n3** [comment]
> to test properly the functionality, we should be able to pass different configurations to the embedded ql, any clue?

If you mean env vars & config files by "configurations", then we should be able to replicate the exact config in the Docker files setting env vars & config files over here:

https://github.com/orchestracities/ngsi-timeseries-api/blob/master/src/reporter/tests/embedded_server.py#L55

Or did you have something more sophisticated in mind?

**Comment by chicco785** [comment]
@c0c0n3 i propose to merge this as third

File: Pipfile [hunk 2]
```diff
@@ -31,6 +31,7 @@ pytest-flask = "~=0.10"
 pytest = "~=3.0"
 pytest-cov = "~=2.7.1"
 coveralls = "~=2.0"
+lovely-pytest-docker = "~=0.2.0"
```
Comment (c0c0n3) [inline Pipfile:34]: this could cause trouble w/ the changes in #461 since it triggered a change in `Pipfile.lock` which was updated in #461  too. one way forward could be to check out this branch, get rid of this line, override `Pipfile.lock` with the one in `master`, then add the above line back in, regenerate `Pipfile.lock`, then commit?

**Review by c0c0n3 — COMMENTED** [review]
It looks like this PR will still need some work before we can merge it b/c it could bring about inconsistencies w/r/t #461 that we merged earlier, see my comments above...

File: Pipfile (hunk 2 above)
Comment (chicco785) [reply Pipfile:34]: i rebased it on top of master, so this should be fine

File: .circleci/config.yml [hunk 3]
```diff
@@ -19,7 +19,7 @@ jobs:
       - run:
           command: |
             export WORKON_HOME=~/.venv
-            pip3 install pipenv
+            pip install pipenv
```
[the remark this answers is not in the document]
Comment (chicco785) [reply .circleci/config.yml:22]: i know but the build on master broke :/ i guess it worked before because of the cache (it was a change i introduced after)

File: Pipfile (hunk 2 above)
Comment (c0c0n3) [reply Pipfile:34]: apparently not:

https://github.com/orchestracities/ngsi-timeseries-api/compare/fix-444...fix-446

ouch! :-)

File: .circleci/config.yml (hunk 3 above)
[the remark this answers is not in the document]
Comment (c0c0n3) [reply .circleci/config.yml:22]: oh dear

**Review by c0c0n3 — APPROVED** [review]
